crate := "pgtest-utils"

# List available recipes
help:
    @just --list --unsorted

# Format this crate
fmt:
    cargo +nightly fmt -p {{crate}}

# Check this crate's formatting without changing files
fmt-check:
    cargo +nightly fmt -p {{crate}} --check

# Run Clippy on all targets in this crate
lint:
    cargo clippy -p {{crate}} --all-targets -- -D warnings

# Run cargo check on this crate
check:
    cargo check -p {{crate}} --all-targets

# Run cargo build on this crate
build:
    cargo build -p {{crate}} --all-targets

# Run cargo test on this crate
test:
    cargo test -p {{crate}}

# Build and open the docs of this crate
doc:
    cargo doc -p {{crate}} --no-deps --open
