[package]
name = "pgtest-server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
mimalloc = "0.1.52"
hotpath = { workspace = true, features = ["sqlx"] }
anyhow = { workspace = true }
envconfig = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
pgtest-core = { path = "../pgtest-core"}
pgtest-wire = { path = "../pgtest-wire"}
pgtest-database-operations = { path = "../pgtest-database-operations"}

[features]
default = []
hotpath = ["hotpath/hotpath", "pgtest-core/hotpath", "pgtest-wire/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc", "pgtest-core/hotpath-alloc", "pgtest-wire/hotpath-alloc"]
hotpath-prometheus = ["hotpath/hotpath-prometheus", "pgtest-core/hotpath-prometheus", "pgtest-wire/hotpath-prometheus"]
