crate := "pgtest-core"

# List available recipes
help:
    @just --list --unsorted --list-prefix '  ' --list-heading $'pgTest Core\n'

# Run lints on this crate (cargo fmt and clippy)
lint:
    cargo +nightly fmt -p {{crate}} --check
    cargo clippy -p {{crate}} --all-targets -- -D warnings

# Run cargo check on this crate
check:
    cargo check -p {{crate}}

# Run cargo build on this crate
build:
    cargo build -p {{crate}} --all-targets

# Run cargo test on this crate
test:
    cargo test -p {{crate}}

test-debug:
    RUST_LOG=debug cargo test -p {{crate}} -- --show-output

# Build and open the docs of this crate
doc:
    cargo doc -p {{crate}} --no-deps --open
